export const {
  AUTH0_ID = '',
  AUTH0_SECRET = '',
  APPLE_ID = '',
  APPLE_TEAM_ID = '',
  APPLE_PRIVATE_KEY = '',
  APPLE_KEY_ID = '',
  EMAIL_SERVER = '',
  EMAIL_FROM = '',
  FACEBOOK_ID = '',
  FACEBOOK_SECRET = '',
  FACEBOOK_CALLBACK_URL = '',
  GITHUB_ID = '',
  GITHUB_SECRET = '',
  GITHUB_CALLBACK_URL = '',
  GOOGLE_ID = '',
  GOOGLE_SECRET = '',
  GOOGLE_CALLBACK_URL = '',
  NEXT_PUBLIC_NODE_ENV = 'development',
  SECRET = '',
  TWITTER_ID = '',
  TWITTER_SECRET = '',
} = process.env;

export const AppConfig = {
  site_name: 'Starter',
  title: 'Nextjs Starter',
  description: 'Starter code for your Nextjs Boilerplate with Tailwind CSS',
  locale: 'en',
};
